### PR TITLE
Fix assorted file/path handling bugs

### PR DESCRIPTION
**Pull request by kastiglione**
Hey Clay,

I ran into a few problems using `motion_require` with files in `app/`, which are relative paths. This patch fixes the problems I ran into. I haven't tested these changes on a gem, like Formotion.
1. Add to app.files by union, to avoid duplicates in file list.
2. Prefix relative files with ./ to match RubyMotion build system.
3. Preserve relative/absolute-ness when generating path of required file.

### CODE REVIEW

**Comment by clayallsopp** [comment]
Gotcha; makes sense. Merged, will update version ASAP

**Comment by clayallsopp** [comment]
Yeah so this does actually break Formotion's build. It's turning

`/Users/clayallsopp/Projects/Motion/Formation/lib/formotion/exceptions.rb` into `.//Users/clayallsopp/Projects/Motion/Formation/lib/formotion/exceptions.rb`

will add some specs so this doesn't happen in the future

**Comment by kastiglione** [comment]
I see the mistake. I just pushed to the same branch. Do I need to do another PR?

**Comment by kastiglione** [comment]
Looks like I do need to. New one coming.

**Comment by clayallsopp** [comment]
So you also need to keep the `File.expand_path` so stuff like `motion_require "../this"` works; now I'm getting

`ERROR! Can't resolve dependency /Users/clayallsopp/Projects/Motion/Formation/lib/formotion/controller/../patch/ui_text_field.rb`

**Comment by kastiglione** [comment]
Ok, I had removed `File.expand_path` to appease RM's picky dependency handling. For relative files in `app/`, using `File.expand_path` was assigning a dependency to the absolute path, but `app.files` contains only the relative path.

**Comment by kastiglione** [comment]
See #4

**Pull request merged**
