### PR TITLE
Add files immediately prior to those in ./app

### PR DESCRIPTION
**Pull request by kastiglione**
Previously, when requiring files, they were appended to `app.files`. With this change, requiring files will have them precede the app's files.

This works for multiple requires, the first requires get first priority.

This was brought up in:
https://groups.google.com/d/msg/rubymotion/WxXBx6lXx0E/9KZmpZ6Cyv0J

I haven't tested this, but it seems like a good default behavior.

### CODE REVIEW

**Comment by DougPuchalski** [comment]
You rock.

**Comment by clayallsopp** [comment]
Lol I made another change right before you committed this, will revert that and merge this ASAP. Thanks man :+1:

**Comment by kastiglione** [comment]
Thanks fellas. A bit of testing would be prudent.

**Comment by clayallsopp** [comment]
Merged

**Pull request merged**
